// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3V2KMQfQ9T14fDYluf8N39mml7AUq-TI',
    appId: '1:778804429853:web:6ef071fbbb9b0d700032f4',
    messagingSenderId: '778804429853',
    projectId: 'flutter1-ea5bb',
    authDomain: 'flutter1-ea5bb.firebaseapp.com',
    storageBucket: 'flutter1-ea5bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFpOxdAEkJZtd_EC7zUPk2UQmJo8Tq_cQ',
    appId: '1:778804429853:android:84d59e550da91cbe0032f4',
    messagingSenderId: '778804429853',
    projectId: 'flutter1-ea5bb',
    storageBucket: 'flutter1-ea5bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6zqeGJ6TnxkFQpEZSvVQNcNtD25cgBRg',
    appId: '1:778804429853:ios:960927692362c0620032f4',
    messagingSenderId: '778804429853',
    projectId: 'flutter1-ea5bb',
    storageBucket: 'flutter1-ea5bb.appspot.com',
    iosClientId: '778804429853-lilfnid88sek083ii13hie5vos0ai52l.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );
}
